# Практическое занятие 1  
## Сбор данных с различных источников: CSV, JSON и табличные данные

### Тема занятия
**"Сбор данных с различных источников."**

## Цель занятия

Научиться получать данные из простых источников, приводить их к табличному виду и выполнять первичный анализ.

После занятия слушатели должны понимать:

1. Что такое источник данных;
2. Чем отличаются CSV, JSON и обычная таблица;
3. Как загрузить данные в Python;
4. Как посмотреть структуру данных;
5. Как выполнить простые расчёты;
6. Как подготовить данные для дальнейшей работы с SQL.

# План занятия

| Этап | Время | Содержание |
|---|---:|---|
| 1 | 10 минут | Введение: какие бывают источники данных |
| 2 | 25 минут | Работа с CSV-файлом на примере данных о студентах |
| 3 | 25 минут | Работа с JSON на примере новостей |
| 4 | 20 минут | Работа с табличными данными пользователей |
| 5 | 10 минут | Итоги, вопросы, мини-задание для закрепления |

---

## Общая логика занятия

В аналитике данных часто используется последовательность:

**Получили данные → Загрузили данные → Проверили структуру → Очистили/подготовили → Проанализировали → Сохранили результат**

На этой паре мы работаем с первыми этапами этой цепочки.

# 1. Введение: какие бывают источники данных

Источник данных — это место, откуда аналитик получает информацию для дальнейшей обработки и анализа.

Примеры источников данных:

- CSV-файлы;
- Excel-файлы;
- JSON-файлы;
- API;
- HTML-страницы;
- базы данных;
- логи сайтов и приложений;
- данные опросов;
- открытые государственные данные;
- данные датчиков и IoT-устройств.

На первой паре мы разберём самые простые и понятные источники:

1. **CSV** — табличный текстовый файл.
2. **JSON** — формат, часто используемый в API.
3. **DataFrame** — таблица в Python, с которой удобно работать при анализе данных.

# 2. Подготовка рабочей среды

В Google Colab уже установлены основные библиотеки, которые понадобятся для занятия.

Сегодня мы будем использовать библиотеку **pandas**.

`pandas` — это библиотека Python для работы с табличными данными.  
Она позволяет загружать данные, смотреть таблицы, фильтровать строки, группировать данные и выполнять расчёты.

In [1]:
# Импортируем библиотеку pandas.
# Обычно её сокращённо называют pd — это стандартная практика в аналитике данных.

import pandas as pd

# Дополнительно импортируем json для работы с JSON-данными.
import json

Проверим, что библиотека pandas подключена корректно.

In [2]:
# Выведем версию pandas.
# Если версия отобразилась, значит библиотека подключена успешно.

pd.__version__

'2.0.1'

# 3. Часть 1. Работа с CSV-файлом

## Что такое CSV?

**CSV** расшифровывается как **Comma-Separated Values**, то есть «значения, разделённые запятыми».

CSV-файл — это простой текстовый файл, который хранит данные в виде таблицы.

Пример:

```text
Фамилия,Имя,Возраст,Специальность
Иванов,Александр,21,Программирование
Петрова,Анна,20,Экономика
```

Каждая строка — это отдельная запись.  
Каждый столбец отделяется запятой или другим разделителем.

В реальной практике CSV часто используют для выгрузок из CRM, Excel, сайтов, баз данных и аналитических систем.

## Задание 1. Создаём CSV-файл со студентами

На практике данные могут быть уже загружены из внешнего источника.  
Но для учебного занятия мы сначала создадим небольшой CSV-файл прямо в Colab, чтобы все слушатели работали с одинаковыми данными.

In [3]:
# Создадим текст CSV-файла.
# Первая строка — это названия столбцов.
# Остальные строки — это данные о студентах.

students_csv = '''Фамилия,Имя,Возраст,Специальность
Иванов,Александр,21,Программирование
Петрова,Анна,20,Экономика
Кузнецов,Сергей,22,Биология
Сергеев,Дмитрий,21,Программирование
Романова,Елена,20,Экономика
Николаев,Павел,23,Биология
'''

# Сохраним текст в файл students.csv.
# encoding='utf-8' нужен, чтобы корректно сохранялись русские буквы.

with open('students.csv', 'w', encoding='utf-8') as file:
    file.write(students_csv)

print('Файл students.csv создан успешно.')

Файл students.csv создан успешно.

## Задание 2. Загружаем CSV-файл

Теперь загрузим созданный файл с помощью `pd.read_csv()`.

Функция `read_csv()` читает CSV-файл и превращает его в DataFrame.

**DataFrame** — это таблица в pandas.

In [4]:
# Загружаем CSV-файл в DataFrame.

students = pd.read_csv('students.csv')

# Выводим таблицу.
students

    Фамилия        Имя  Возраст     Специальность
0    Иванов  Александр       21  Программирование
1   Петрова       Анна       20         Экономика
2  Кузнецов     Сергей       22          Биология
3   Сергеев    Дмитрий       21  Программирование
4  Романова      Елена       20         Экономика
5  Николаев      Павел       23          Биология

## Задание 3. Просмотр первых строк таблицы

В больших наборах данных таблица может содержать тысячи или миллионы строк.  
Поэтому обычно сначала смотрят не всю таблицу, а только первые строки.

Для этого используется метод `.head()`.

In [5]:
# Метод head() показывает первые 5 строк таблицы по умолчанию.

students.head()

    Фамилия        Имя  Возраст     Специальность
0    Иванов  Александр       21  Программирование
1   Петрова       Анна       20         Экономика
2  Кузнецов     Сергей       22          Биология
3   Сергеев    Дмитрий       21  Программирование
4  Романова      Елена       20         Экономика

Можно указать количество строк, которое нужно вывести.

In [6]:
# Покажем первые 3 строки.

students.head(3)

    Фамилия        Имя  Возраст     Специальность
0    Иванов  Александр       21  Программирование
1   Петрова       Анна       20         Экономика
2  Кузнецов     Сергей       22          Биология

## Задание 4. Проверяем размер таблицы

Метод `.shape` показывает размер таблицы:

- первое число — количество строк;
- второе число — количество столбцов.

In [7]:
# Проверяем размер таблицы.

students.shape

(6, 4)

In [8]:
# Чтобы вывод был понятнее, можно отдельно сохранить количество строк и столбцов.

rows, columns = students.shape

print('Количество строк:', rows)
print('Количество столбцов:', columns)

Количество строк: 6
Количество столбцов: 4

## Задание 5. Проверяем типы данных

Метод `.info()` показывает:

- названия столбцов;
- количество непустых значений;
- типы данных;
- объём памяти, который занимает таблица.

Это один из первых методов, который аналитик применяет после загрузки данных.

In [9]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Фамилия        6 non-null      object
 1   Имя            6 non-null      object
 2   Возраст        6 non-null      int64
 3   Специальность  6 non-null      object
dtypes: int64(1), object(3)
memory usage: 320.0+ bytes

Обратите внимание на тип столбца `Возраст`.

Если pandas распознал его как `int64`, значит значения воспринимаются как числа, и по ним можно считать среднее, минимум, максимум и другие показатели.

## Задание 6. Считаем количество студентов

Для подсчёта количества строк можно использовать:

- `.shape[0]`;
- `len()`;
- `.count()` для непустых значений по столбцам.

В этом занятии используем простой способ через `len()`.

In [10]:
# Количество студентов — это количество строк в таблице.

students_count = len(students)

print('Количество студентов:', students_count)

Количество студентов: 6

## Задание 7. Считаем средний возраст студентов

Для расчёта среднего значения используется метод `.mean()`.

In [11]:
# Считаем средний возраст по столбцу Возраст.

average_age = students['Возраст'].mean()

print('Средний возраст студентов:', average_age)

Средний возраст студентов: 21.166666666666668

Чтобы результат выглядел аккуратнее, можно округлить значение.

In [12]:
# Округлим средний возраст до двух знаков после запятой.

average_age = round(students['Возраст'].mean(), 2)

print('Средний возраст студентов:', average_age)

Средний возраст студентов: 21.17

## Задание 8. Группировка по специальности

Теперь посчитаем средний возраст отдельно по каждой специальности.

Для этого используется метод `.groupby()`.

Логика такая:

1. сгруппировать строки по специальности;
2. взять столбец `Возраст`;
3. посчитать среднее значение.

In [13]:
# Группируем данные по специальности и считаем средний возраст.

avg_age_by_specialty = students.groupby('Специальность')['Возраст'].mean()

avg_age_by_specialty

Специальность
Биология            22.5
Программирование    21.0
Экономика           20.0
Name: Возраст, dtype: float64

Результат можно сделать более удобным для чтения, превратив его обратно в таблицу.

In [14]:
# reset_index() превращает результат группировки обратно в обычную таблицу.

avg_age_by_specialty = students.groupby('Специальность')['Возраст'].mean().reset_index()

# Переименуем столбец, чтобы название было понятнее.
avg_age_by_specialty = avg_age_by_specialty.rename(columns={'Возраст': 'Средний возраст'})

avg_age_by_specialty

      Специальность  Средний возраст
0          Биология             22.5
1  Программирование             21.0
2         Экономика             20.0

## Мини-обсуждение после CSV-блока

Ответьте на вопросы:

1. Что такое CSV-файл?
2. Почему CSV удобно использовать для передачи табличных данных?
3. Что делает функция `pd.read_csv()`?
4. Зачем после загрузки данных смотреть `.head()`, `.shape` и `.info()`?
5. Что делает `.groupby()`?

---

## Промежуточный вывод

Мы загрузили данные из CSV-файла, посмотрели структуру таблицы и рассчитали простые показатели.  
Это первый шаг в работе аналитика: получить данные и убедиться, что они загружены корректно.

# 4. Часть 2. Работа с JSON

## Что такое JSON?

**JSON** расшифровывается как **JavaScript Object Notation**.

JSON часто используется:

- в API;
- на сайтах;
- в мобильных приложениях;
- в системах обмена данными.

JSON может хранить данные в виде списков и объектов.

Пример одного объекта:

```json
{
  "title": "Запущен новый сервис аналитики данных",
  "author": "Иван Петров",
  "date": "2026-05-10"
}
```

Для аналитика важно уметь преобразовывать JSON в таблицу.

## Задание 9. Создаём JSON-файл с новостями

Создадим небольшой набор данных с новостями.

Каждая новость содержит:

- заголовок;
- автора;
- дату публикации;
- категорию.

In [15]:
# Создаём список словарей.
# Каждый словарь — это одна новость.

news_data = [
    {
        'title': 'Запущен новый сервис аналитики данных',
        'author': 'Иван Петров',
        'date': '2026-05-10',
        'category': 'Технологии'
    },
    {
        'title': 'Компании переходят на отечественные ИТ-решения',
        'author': 'Анна Смирнова',
        'date': '2026-05-12',
        'category': 'Бизнес'
    },
    {
        'title': 'Рынок Data Analytics продолжает расти',
        'author': 'Иван Петров',
        'date': '2026-05-15',
        'category': 'Аналитика'
    },
    {
        'title': 'Новые инструменты визуализации данных становятся популярнее',
        'author': 'Мария Соколова',
        'date': '2026-05-18',
        'category': 'Технологии'
    }
]

# Сохраняем данные в JSON-файл.
# ensure_ascii=False нужен, чтобы русские буквы сохранялись нормально.
# indent=4 делает файл более читаемым.

with open('news.json', 'w', encoding='utf-8') as file:
    json.dump(news_data, file, ensure_ascii=False, indent=4)

print('Файл news.json создан успешно.')

Файл news.json создан успешно.

## Задание 10. Загружаем JSON-файл

Для загрузки JSON можно использовать функцию `pd.read_json()`.

In [16]:
# Загружаем JSON-файл в DataFrame.

news = pd.read_json('news.json')

# Выводим таблицу.
news

,title,author,date,category
0,Запущен новый сервис аналитики данных,Иван Петров,2026-05-10,Технологии
1,Компании переходят на отечественные ИТ-решения,Анна Смирнова,2026-05-12,Бизнес
2,Рынок Data Analytics продолжает расти,Иван Петров,2026-05-15,Аналитика
3,Новые инструменты визуализации данных становят...,Мария Соколова,2026-05-18,Технологии

## Задание 11. Проверяем структуру данных

Как и в CSV-блоке, после загрузки данных нужно проверить:

- первые строки;
- размер таблицы;
- типы данных.

In [17]:
# Первые строки таблицы.

news.head()

,title,author,date,category
0,Запущен новый сервис аналитики данных,Иван Петров,2026-05-10,Технологии
1,Компании переходят на отечественные ИТ-решения,Анна Смирнова,2026-05-12,Бизнес
2,Рынок Data Analytics продолжает расти,Иван Петров,2026-05-15,Аналитика
3,Новые инструменты визуализации данных становят...,Мария Соколова,2026-05-18,Технологии

In [18]:
# Размер таблицы.

news.shape

(4, 4)

In [19]:
# Информация о столбцах и типах данных.

news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     4 non-null      object
 1   author    4 non-null      object
 2   date      4 non-null      datetime64[ns]
 3   category  4 non-null      object
dtypes: datetime64[ns](1), object(3)
memory usage: 256.0+ bytes

Обратите внимание: столбец `date` может быть распознан как дата или как обычный текст.  
Если дата нужна для фильтрации по времени, её часто специально преобразуют в тип `datetime`.

In [20]:
# Преобразуем столбец date в тип datetime.
# Это позволит в дальнейшем удобно фильтровать данные по датам.

news['date'] = pd.to_datetime(news['date'])

news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     4 non-null      object
 1   author    4 non-null      object
 2   date      4 non-null      datetime64[ns]
 3   category  4 non-null      object
dtypes: datetime64[ns](1), object(3)
memory usage: 256.0+ bytes

## Задание 12. Фильтрация новостей по автору

Отберём только новости автора «Иван Петров».

In [21]:
# Фильтруем строки, где автор равен 'Иван Петров'.

ivan_news = news[news['author'] == 'Иван Петров']

ivan_news

                                   title       author       date    category
0  Запущен новый сервис аналитики данных  Иван Петров 2026-05-10  Технологии
2  Рынок Data Analytics продолжает расти  Иван Петров 2026-05-15   Аналитика

## Задание 13. Фильтрация новостей по категории

Теперь отберём новости из категории «Технологии».

In [22]:
# Фильтруем новости по категории.

tech_news = news[news['category'] == 'Технологии']

tech_news

,title,author,date,category
0,Запущен новый сервис аналитики данных,Иван Петров,2026-05-10,Технологии
3,Новые инструменты визуализации данных становят...,Мария Соколова,2026-05-18,Технологии

## Задание 14. Фильтрация новостей по дате

Найдём новости, опубликованные после 12 мая 2026 года.

In [23]:
# Фильтруем новости по дате.
# Так как столбец date уже преобразован в datetime, сравнение работает корректно.

recent_news = news[news['date'] > '2026-05-12']

recent_news

,title,author,date,category
2,Рынок Data Analytics продолжает расти,Иван Петров,2026-05-15,Аналитика
3,Новые инструменты визуализации данных становят...,Мария Соколова,2026-05-18,Технологии

## Задание 15. Сохраняем результат в CSV

После фильтрации часто нужно сохранить результат для передачи, отчёта или дальнейшей загрузки в базу данных.

Сохраним новости автора «Иван Петров» в отдельный CSV-файл.

In [24]:
# Сохраняем DataFrame в CSV.
# index=False означает, что pandas не будет добавлять отдельный столбец с индексами строк.

ivan_news.to_csv('ivan_news.csv', index=False, encoding='utf-8')

print('Файл ivan_news.csv создан успешно.')

Файл ivan_news.csv создан успешно.

Проверим, что файл действительно сохранился и корректно читается.

In [25]:
# Загружаем сохранённый файл обратно.

check_ivan_news = pd.read_csv('ivan_news.csv')

check_ivan_news

                                   title       author        date    category
0  Запущен новый сервис аналитики данных  Иван Петров  2026-05-10  Технологии
1  Рынок Data Analytics продолжает расти  Иван Петров  2026-05-15   Аналитика

## Мини-обсуждение после JSON-блока

Ответьте на вопросы:

1. Что такое JSON?
2. Почему JSON часто используется в API?
3. Чем JSON отличается от CSV?
4. Зачем преобразовывать JSON в таблицу?
5. Зачем преобразовывать дату в тип `datetime`?
6. Почему результат фильтрации иногда нужно сохранять в отдельный файл?

---

## Промежуточный вывод

Мы научились загружать JSON, преобразовывать его в таблицу, фильтровать данные и сохранять результат в CSV.  
Это важный навык, потому что многие внешние сервисы и API возвращают данные именно в JSON-формате.

# 5. Часть 3. Работа с табличными данными пользователей

Теперь создадим таблицу пользователей, которая будет использоваться как подготовка к теме SQL.

На следующих парах эти данные можно будет загрузить в базу данных и выполнять SQL-запросы:

- `SELECT`;
- `WHERE`;
- `ORDER BY`;
- `GROUP BY`;
- `JOIN`.

Сегодня наша задача — подготовить данные и проверить их качество.

## Задание 16. Создаём таблицу пользователей

Создадим таблицу `users`.

Поля таблицы:

- `id` — уникальный идентификатор пользователя;
- `name` — имя;
- `email` — электронная почта;
- `age` — возраст;
- `country` — страна;
- `balance` — баланс.

In [26]:
# Создаём данные пользователей в виде списка словарей.

users_data = [
    {'id': 1, 'name': 'Ivan', 'email': 'ivan@example.com', 'age': 25, 'country': 'RUS', 'balance': 100000},
    {'id': 2, 'name': 'Gleb', 'email': 'gleb@example.com', 'age': 26, 'country': 'RUS', 'balance': 90000},
    {'id': 3, 'name': 'Sergey', 'email': 'sergey@example.com', 'age': 28, 'country': 'RUS', 'balance': 90000},
    {'id': 4, 'name': 'Andrew', 'email': 'andrew@example.com', 'age': 24, 'country': 'RUS', 'balance': 95000},
    {'id': 5, 'name': 'Bob', 'email': 'bob@example.com', 'age': 25, 'country': 'USA', 'balance': 100000},
    {'id': 6, 'name': 'Tom', 'email': 'tom@example.com', 'age': 29, 'country': 'USA', 'balance': 110000}
]

# Преобразуем список словарей в DataFrame.

users = pd.DataFrame(users_data)

users

   id    name               email  age country  balance
0   1    Ivan    ivan@example.com   25     RUS   100000
1   2    Gleb    gleb@example.com   26     RUS    90000
2   3  Sergey  sergey@example.com   28     RUS    90000
3   4  Andrew  andrew@example.com   24     RUS    95000
4   5     Bob     bob@example.com   25     USA   100000
5   6     Tom     tom@example.com   29     USA   110000

## Задание 17. Проверяем структуру таблицы

Перед анализом нужно убедиться, что таблица создана корректно.

In [27]:
# Смотрим первые строки.

users.head()

   id    name               email  age country  balance
0   1    Ivan    ivan@example.com   25     RUS   100000
1   2    Gleb    gleb@example.com   26     RUS    90000
2   3  Sergey  sergey@example.com   28     RUS    90000
3   4  Andrew  andrew@example.com   24     RUS    95000
4   5     Bob     bob@example.com   25     USA   100000

In [28]:
# Проверяем размер таблицы.

users.shape

(6, 6)

In [29]:
# Проверяем типы данных.

users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       6 non-null      int64
 1   name     6 non-null      object
 2   email    6 non-null      object
 3   age      6 non-null      int64
 4   country  6 non-null      object
 5   balance  6 non-null      int64
dtypes: int64(3), object(3)
memory usage: 416.0+ bytes

## Задание 18. Проверяем пропущенные значения

Пропущенные значения могут мешать анализу.

Для проверки используется метод `.isna()`.

Если добавить `.sum()`, мы получим количество пропусков по каждому столбцу.

In [30]:
# Проверяем количество пропущенных значений по каждому столбцу.

users.isna().sum()

id         0
name       0
email      0
age        0
country    0
balance    0
dtype: int64

Если по всем столбцам стоит 0, значит пропущенных значений нет.

## Задание 19. Проверяем уникальность идентификаторов

Поле `id` должно быть уникальным.

В базах данных такое поле часто используется как первичный ключ.

In [31]:
# Проверяем, все ли значения id уникальны.

users['id'].is_unique

True

In [32]:
# Посмотрим количество уникальных id и общее количество строк.

unique_ids = users['id'].nunique()
total_rows = len(users)

print('Количество уникальных id:', unique_ids)
print('Количество строк:', total_rows)

Количество уникальных id: 6
Количество строк: 6

Если количество уникальных `id` равно количеству строк, значит каждый пользователь имеет свой уникальный идентификатор.

## Задание 20. Простые аналитические расчёты по пользователям

Рассчитаем несколько показателей:

1. количество пользователей;
2. средний возраст;
3. средний баланс;
4. максимальный баланс;
5. минимальный баланс.

In [33]:
print('Количество пользователей:', len(users))
print('Средний возраст:', round(users['age'].mean(), 2))
print('Средний баланс:', round(users['balance'].mean(), 2))
print('Максимальный баланс:', users['balance'].max())
print('Минимальный баланс:', users['balance'].min())

Количество пользователей: 6
Средний возраст: 26.17
Средний баланс: 97500.0
Максимальный баланс: 110000
Минимальный баланс: 90000

## Задание 21. Группировка пользователей по странам

Посчитаем:

1. количество пользователей по странам;
2. средний баланс по странам;
3. средний возраст по странам.

In [34]:
# Количество пользователей по странам.

users_by_country = users.groupby('country')['id'].count().reset_index()

users_by_country = users_by_country.rename(columns={'id': 'users_count'})

users_by_country

  country  users_count
0     RUS            4
1     USA            2

In [35]:
# Средний баланс по странам.

avg_balance_by_country = users.groupby('country')['balance'].mean().reset_index()

avg_balance_by_country = avg_balance_by_country.rename(columns={'balance': 'avg_balance'})

avg_balance_by_country

  country  avg_balance
0     RUS      93750.0
1     USA     105000.0

In [36]:
# Средний возраст по странам.

avg_age_by_country = users.groupby('country')['age'].mean().reset_index()

avg_age_by_country = avg_age_by_country.rename(columns={'age': 'avg_age'})

avg_age_by_country

  country  avg_age
0     RUS    25.75
1     USA    27.00

## Задание 22. Сохраняем таблицу пользователей

Сохраним таблицу `users` в CSV-файл.  
На следующих парах этот файл можно использовать для загрузки данных в SQL.

In [37]:
# Сохраняем таблицу пользователей в CSV.

users.to_csv('users.csv', index=False, encoding='utf-8')

print('Файл users.csv создан успешно.')

Файл users.csv создан успешно.

Проверим, что файл корректно читается.

In [38]:
# Загружаем сохранённый файл обратно.

users_check = pd.read_csv('users.csv')

users_check

   id    name               email  age country  balance
0   1    Ivan    ivan@example.com   25     RUS   100000
1   2    Gleb    gleb@example.com   26     RUS    90000
2   3  Sergey  sergey@example.com   28     RUS    90000
3   4  Andrew  andrew@example.com   24     RUS    95000
4   5     Bob     bob@example.com   25     USA   100000
5   6     Tom     tom@example.com   29     USA   110000

# 6. Итоговое мини-задание для закрепления

Выполните самостоятельно или вместе с преподавателем.

## Задание

Используя таблицу `users`, выполните действия:

1. Выведите только столбцы `name`, `country`, `balance`.
2. Найдите пользователей из страны `RUS`.
3. Найдите пользователей с балансом больше 95 000.
4. Отсортируйте пользователей по балансу по убыванию.
5. Посчитайте средний баланс пользователей по каждой стране.
6. Сохраните результат группировки в файл `country_balance.csv`.

## Решение мини-задания

Ниже приведено подробное решение.

In [39]:
# 1. Выводим только нужные столбцы.

users[['name', 'country', 'balance']]

     name country  balance
0    Ivan     RUS   100000
1    Gleb     RUS    90000
2  Sergey     RUS    90000
3  Andrew     RUS    95000
4     Bob     USA   100000
5     Tom     USA   110000

In [40]:
# 2. Находим пользователей из страны RUS.

users_rus = users[users['country'] == 'RUS']

users_rus

   id    name               email  age country  balance
0   1    Ivan    ivan@example.com   25     RUS   100000
1   2    Gleb    gleb@example.com   26     RUS    90000
2   3  Sergey  sergey@example.com   28     RUS    90000
3   4  Andrew  andrew@example.com   24     RUS    95000

In [41]:
# 3. Находим пользователей с балансом больше 95 000.

users_high_balance = users[users['balance'] > 95000]

users_high_balance

   id  name             email  age country  balance
0   1  Ivan  ivan@example.com   25     RUS   100000
4   5   Bob   bob@example.com   25     USA   100000
5   6   Tom   tom@example.com   29     USA   110000

In [42]:
# 4. Сортируем пользователей по балансу по убыванию.

users_sorted = users.sort_values(by='balance', ascending=False)

users_sorted

   id    name               email  age country  balance
5   6     Tom     tom@example.com   29     USA   110000
0   1    Ivan    ivan@example.com   25     RUS   100000
4   5     Bob     bob@example.com   25     USA   100000
3   4  Andrew  andrew@example.com   24     RUS    95000
1   2    Gleb    gleb@example.com   26     RUS    90000
2   3  Sergey  sergey@example.com   28     RUS    90000

In [43]:
# 5. Считаем средний баланс пользователей по каждой стране.

country_balance = users.groupby('country')['balance'].mean().reset_index()

country_balance = country_balance.rename(columns={'balance': 'avg_balance'})

country_balance

  country  avg_balance
0     RUS      93750.0
1     USA     105000.0

In [44]:
# 6. Сохраняем результат в CSV-файл.

country_balance.to_csv('country_balance.csv', index=False, encoding='utf-8')

print('Файл country_balance.csv создан успешно.')

Файл country_balance.csv создан успешно.

# 7. Контрольные вопросы по первой паре

Ответьте на вопросы:

1. Что такое источник данных?
2. Какие источники данных мы рассмотрели на занятии?
3. Что такое CSV?
4. Что такое JSON?
5. Чем JSON отличается от CSV?
6. Что такое DataFrame?
7. Для чего используется метод `.head()`?
8. Для чего используется метод `.info()`?
9. Как проверить количество строк и столбцов?
10. Как проверить пропущенные значения?
11. Что делает метод `.groupby()`?
12. Почему перед загрузкой данных в SQL нужно проверить таблицу?

# 8. Итог пары

На первой паре мы изучили базовые способы получения и подготовки данных.

Мы научились:

- создавать и загружать CSV-файлы;
- читать JSON-файлы;
- преобразовывать JSON в таблицу;
- просматривать структуру данных;
- проверять типы данных;
- проверять пропущенные значения;
- выполнять простые расчёты;
- группировать данные;
- сохранять результаты в CSV.

## Связь со следующими парами

На второй паре мы перейдём к данным из HTML-источников и разберём основы web scraping.

На третьей и четвёртой парах подготовленные табличные данные будут использоваться для изучения SQL.