# Практическое занятие 3  
## Основы SQL: SELECT, WHERE, ORDER BY, агрегатные функции и GROUP BY

### Тема занятия
**"Основы работы с SQL."**

## Цель занятия

Научиться выполнять базовые SQL-запросы по одной таблице.

После занятия слушатели должны понимать:

1. что такое база данных;
2. что такое таблица, строка и столбец;
3. что такое первичный ключ;
4. как создать таблицу;
5. как добавить данные;
6. как выполнять SQL-запросы;
7. как фильтровать, сортировать и группировать данные;
8. как использовать агрегатные функции.

# План пары

| Этап | Время | Содержание |
|---|---:|---|
| 1 | 10 минут | Повторение первых двух пар и введение в SQL |
| 2 | 10 минут | Создание SQLite-базы и таблицы `users` |
| 3 | 15 минут | Базовые запросы `SELECT` |
| 4 | 20 минут | Фильтрация данных: `WHERE`, `AND`, `OR`, `BETWEEN` |
| 5 | 15 минут | Сортировка: `ORDER BY`, `LIMIT` |
| 6 | 15 минут | Агрегатные функции: `COUNT`, `AVG`, `SUM`, `MIN`, `MAX` |
| 7 | 5 минут | Группировка: `GROUP BY` и итоги |

---

## Связь с предыдущими парами

На первой паре мы работали с простыми источниками данных: CSV, JSON и табличными данными.

На второй паре мы извлекали данные из HTML и приводили их к табличному виду.

Теперь мы переходим к следующему этапу:

**табличные данные → база данных → SQL-запросы → аналитический результат**

SQL нужен аналитику, чтобы быстро извлекать, фильтровать, группировать и анализировать данные, которые хранятся в базах данных.

# 1. Что такое SQL и база данных

**SQL** — это язык для работы с реляционными базами данных.

С помощью SQL можно:

- создавать таблицы;
- добавлять данные;
- получать данные;
- фильтровать данные;
- сортировать данные;
- группировать данные;
- рассчитывать показатели;
- соединять несколько таблиц.

---

## Основные понятия

| Понятие | Простое объяснение |
|---|---|
| База данных | структурированное хранилище данных |
| Таблица | данные в виде строк и столбцов |
| Строка / запись | один объект, например один пользователь |
| Столбец / поле | характеристика объекта, например имя или возраст |
| Первичный ключ | уникальный идентификатор строки |
| SQL-запрос | команда к базе данных |
| SELECT | команда для получения данных |
| WHERE | условие фильтрации |
| ORDER BY | сортировка |
| GROUP BY | группировка |

# 2. Почему используем SQLite

На этом занятии мы используем **SQLite**.

SQLite — это простая база данных, которая работает прямо внутри Python и Google Colab.

Преимущества SQLite для учебного занятия:

- не нужно устанавливать MySQL;
- не нужен Docker;
- не нужен отдельный сервер;
- все запросы выполняются прямо в ноутбуке;
- базовый SQL-синтаксис похож на MySQL и PostgreSQL.

На следующих этапах эти же принципы можно перенести на MySQL, PostgreSQL и другие СУБД.

# 3. Подготовка рабочей среды

Для занятия нам понадобятся:

1. `sqlite3` — встроенная библиотека Python для работы с SQLite;
2. `pandas` — библиотека для отображения результатов SQL-запросов в виде таблиц.

Также создадим удобную функцию `run_sql()`, чтобы выполнять SQL-запросы и сразу видеть результат в виде DataFrame.

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
# Создаём подключение к базе данных SQLite.
# ':memory:' означает, что база будет создана в оперативной памяти.
# Она будет существовать, пока открыт текущий ноутбук.

connection = sqlite3.connect(':memory:')
cursor = connection.cursor()

print('База данных SQLite создана успешно.')

База данных SQLite создана успешно.

In [ ]:
# Вспомогательная функция для выполнения SELECT-запросов.
# Она принимает SQL-запрос в виде текста и возвращает результат как таблицу pandas.

def run_sql(query):
    return pd.read_sql_query(query, connection)

# 4. Создание таблицы users

Создадим таблицу пользователей `users`.

В таблице будут поля:

| Поле | Тип данных | Описание |
|---|---|---|
| id | INTEGER | уникальный идентификатор пользователя |
| name | TEXT | имя пользователя |
| email | TEXT | электронная почта |
| age | INTEGER | возраст |
| country | TEXT | страна |
| balance | REAL | баланс |

Поле `id` будет первичным ключом.

In [ ]:
# CREATE TABLE — команда создания таблицы.
# PRIMARY KEY означает, что поле id является уникальным идентификатором записи.
# NOT NULL означает, что поле не может быть пустым.

cursor.execute('''
CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    age INTEGER NOT NULL,
    country TEXT NOT NULL,
    balance REAL NOT NULL
);
''')

connection.commit()

print('Таблица users создана успешно.')

Таблица users создана успешно.

# 5. Добавление данных в таблицу

Теперь добавим в таблицу несколько пользователей.

Для добавления данных используется команда `INSERT INTO`.

Общая логика:

```sql
INSERT INTO table_name (column1, column2, column3)
VALUES (value1, value2, value3);
```

In [ ]:
cursor.execute('''
INSERT INTO users (id, name, email, age, country, balance) VALUES
(1, 'Ivan', 'ivan@example.com', 25, 'RUS', 100000),
(2, 'Gleb', 'gleb@example.com', 26, 'RUS', 90000),
(3, 'Sergey', 'sergey@example.com', 28, 'RUS', 90000),
(4, 'Andrew', 'andrew@example.com', 24, 'RUS', 95000),
(5, 'Bob', 'bob@example.com', 25, 'USA', 100000),
(6, 'Tom', 'tom@example.com', 29, 'USA', 110000);
''')

connection.commit()

print('Данные добавлены успешно.')

Данные добавлены успешно.

# 6. Проверка таблицы

После создания таблицы и добавления данных нужно проверить, что всё загрузилось корректно.

In [ ]:
run_sql('''
SELECT *
FROM users;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   6     Tom     tom@example.com   29     USA  110000.0

Если таблица отобразилась, значит база данных создана корректно, и можно переходить к SQL-запросам.

# 7. Базовый SELECT

`SELECT` — основная команда SQL для получения данных из таблицы.

Самый простой запрос:

```sql
SELECT *
FROM users;
```

Звёздочка `*` означает: вывести все столбцы.

In [ ]:
run_sql('''
SELECT *
FROM users;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   6     Tom     tom@example.com   29     USA  110000.0

## Задание 1. Вывести отдельные столбцы

В реальной аналитике часто не нужно выводить все столбцы.  
Можно выбрать только те поля, которые нужны для задачи.

In [ ]:
run_sql('''
SELECT name, age
FROM users;
''')

     name  age
0    Ivan   25
1    Gleb   26
2  Sergey   28
3  Andrew   24
4     Bob   25
5     Tom   29

In [ ]:
run_sql('''
SELECT name, country, balance
FROM users;
''')

     name country   balance
0    Ivan     RUS  100000.0
1    Gleb     RUS   90000.0
2  Sergey     RUS   90000.0
3  Andrew     RUS   95000.0
4     Bob     USA  100000.0
5     Tom     USA  110000.0

## Обсуждение

Ответьте на вопросы:

1. Что делает `SELECT *`?
2. Почему иногда лучше выбирать только отдельные столбцы?
3. Что означает `FROM users`?

# 8. Псевдонимы столбцов: AS

Иногда названия столбцов в результате запроса нужно сделать более понятными.

Для этого используется `AS`.

Пример:

```sql
SELECT name AS user_name
FROM users;
```

In [ ]:
run_sql('''
SELECT
    name AS user_name,
    age AS user_age,
    balance AS user_balance
FROM users;
''')

  user_name  user_age  user_balance
0      Ivan        25      100000.0
1      Gleb        26       90000.0
2    Sergey        28       90000.0
3    Andrew        24       95000.0
4       Bob        25      100000.0
5       Tom        29      110000.0

`AS` особенно полезен, когда мы рассчитываем новые показатели или используем агрегатные функции.

# 9. Фильтрация данных: WHERE

`WHERE` используется, чтобы выбрать только те строки, которые соответствуют условию.

Пример:

```sql
SELECT *
FROM users
WHERE age > 26;
```

Этот запрос выбирает пользователей старше 26 лет.

## Задание 2. Найти пользователей старше 26 лет

In [ ]:
run_sql('''
SELECT *
FROM users
WHERE age > 26;
''')

   id    name               email  age country   balance
0   3  Sergey  sergey@example.com   28     RUS   90000.0
1   6     Tom     tom@example.com   29     USA  110000.0

## Задание 3. Найти пользователей из страны RUS

In [ ]:
run_sql('''
SELECT *
FROM users
WHERE country = 'RUS';
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0

## Задание 4. Найти пользователей с балансом больше 95 000

In [ ]:
run_sql('''
SELECT *
FROM users
WHERE balance > 95000;
''')

   id  name             email  age country   balance
0   1  Ivan  ivan@example.com   25     RUS  100000.0
1   5   Bob   bob@example.com   25     USA  100000.0
2   6   Tom   tom@example.com   29     USA  110000.0

## Важное правило

В SQL текстовые значения пишутся в кавычках:

```sql
WHERE country = 'RUS'
```

Числовые значения пишутся без кавычек:

```sql
WHERE age > 26
```

# 10. Несколько условий: AND и OR

Иногда нужно указать не одно, а несколько условий.

Для этого используются:

- `AND` — должны выполниться оба условия;
- `OR` — должно выполниться хотя бы одно условие.

---

## AND

Пример:

```sql
WHERE country = 'RUS' AND balance > 90000
```

Это означает: страна должна быть `RUS` и одновременно баланс должен быть больше 90 000.

In [ ]:
run_sql('''
SELECT *
FROM users
WHERE country = 'RUS' AND balance > 90000;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   4  Andrew  andrew@example.com   24     RUS   95000.0

## OR

Пример:

```sql
WHERE country = 'USA' OR age < 25
```

Это означает: пользователь либо из `USA`, либо младше 25 лет.

In [ ]:
run_sql('''
SELECT *
FROM users
WHERE country = 'USA' OR age < 25;
''')

   id    name               email  age country   balance
0   4  Andrew  andrew@example.com   24     RUS   95000.0
1   5     Bob     bob@example.com   25     USA  100000.0
2   6     Tom     tom@example.com   29     USA  110000.0

## Обсуждение

Ответьте на вопросы:

1. Чем `AND` отличается от `OR`?
2. Почему условия важно формулировать точно?
3. Как изменится результат, если заменить `AND` на `OR`?

# 11. Диапазоны: BETWEEN

`BETWEEN` используется для отбора значений в диапазоне.

Пример:

```sql
WHERE balance BETWEEN 95000 AND 110000
```

Этот запрос выберет пользователей с балансом от 95 000 до 110 000 включительно.

In [ ]:
run_sql('''
SELECT *
FROM users
WHERE balance BETWEEN 95000 AND 110000;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   4  Andrew  andrew@example.com   24     RUS   95000.0
2   5     Bob     bob@example.com   25     USA  100000.0
3   6     Tom     tom@example.com   29     USA  110000.0

`BETWEEN` удобно использовать для числовых диапазонов, дат, возрастов, цен и сумм.

# 12. Сортировка: ORDER BY

`ORDER BY` используется для сортировки результата.

По умолчанию сортировка идёт по возрастанию.

Пример:

```sql
SELECT *
FROM users
ORDER BY age;
```

## Задание 5. Отсортировать пользователей по возрасту

In [ ]:
run_sql('''
SELECT *
FROM users
ORDER BY age;
''')

   id    name               email  age country   balance
0   4  Andrew  andrew@example.com   24     RUS   95000.0
1   1    Ivan    ivan@example.com   25     RUS  100000.0
2   5     Bob     bob@example.com   25     USA  100000.0
3   2    Gleb    gleb@example.com   26     RUS   90000.0
4   3  Sergey  sergey@example.com   28     RUS   90000.0
5   6     Tom     tom@example.com   29     USA  110000.0

## Задание 6. Отсортировать пользователей по балансу по убыванию

In [ ]:
run_sql('''
SELECT *
FROM users
ORDER BY balance DESC;
''')

   id    name               email  age country   balance
0   6     Tom     tom@example.com   29     USA  110000.0
1   1    Ivan    ivan@example.com   25     RUS  100000.0
2   5     Bob     bob@example.com   25     USA  100000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   2    Gleb    gleb@example.com   26     RUS   90000.0
5   3  Sergey  sergey@example.com   28     RUS   90000.0

## Задание 7. Найти пользователя с самым высоким балансом

In [ ]:
run_sql('''
SELECT *
FROM users
ORDER BY balance DESC
LIMIT 1;
''')

   id name            email  age country   balance
0   6  Tom  tom@example.com   29     USA  110000.0

`DESC` означает сортировку по убыванию.  
`LIMIT` ограничивает количество строк в результате.

## Обсуждение

Ответьте на вопросы:

1. Что делает `ORDER BY`?
2. Чем сортировка `ASC` отличается от `DESC`?
3. Зачем нужен `LIMIT`?

# 13. Агрегатные функции

Агрегатные функции рассчитывают один показатель по набору строк.

Основные агрегатные функции:

| Функция | Что делает |
|---|---|
| COUNT | считает количество строк |
| AVG | считает среднее значение |
| SUM | считает сумму |
| MIN | находит минимальное значение |
| MAX | находит максимальное значение |

## COUNT: общее количество пользователей

In [ ]:
run_sql('''
SELECT COUNT(*) AS users_count
FROM users;
''')

   users_count
0            6

## COUNT с условием: количество пользователей из RUS

In [ ]:
run_sql('''
SELECT COUNT(*) AS rus_users_count
FROM users
WHERE country = 'RUS';
''')

   rus_users_count
0                4

## AVG: средний баланс пользователей

In [ ]:
run_sql('''
SELECT AVG(balance) AS avg_balance
FROM users;
''')

   avg_balance
0      97500.0

## SUM: сумма всех балансов

In [ ]:
run_sql('''
SELECT SUM(balance) AS total_balance
FROM users;
''')

   total_balance
0       585000.0

## MIN и MAX: минимальный и максимальный баланс

In [ ]:
run_sql('''
SELECT
    MIN(balance) AS min_balance,
    MAX(balance) AS max_balance
FROM users;
''')

   min_balance  max_balance
0      90000.0     110000.0

## Несколько агрегатов в одном запросе

In [ ]:
run_sql('''
SELECT
    COUNT(*) AS users_count,
    AVG(age) AS avg_age,
    AVG(balance) AS avg_balance,
    MIN(balance) AS min_balance,
    MAX(balance) AS max_balance
FROM users;
''')

   users_count    avg_age  avg_balance  min_balance  max_balance
0            6  26.166667      97500.0      90000.0     110000.0

## Обсуждение

Ответьте на вопросы:

1. Что такое агрегатная функция?
2. Чем `COUNT` отличается от `SUM`?
3. Почему для аналитика важны `AVG`, `MIN`, `MAX`?
4. Зачем давать столбцам понятные названия через `AS`?

# 14. Группировка: GROUP BY

`GROUP BY` используется, когда нужно посчитать показатели не по всей таблице, а отдельно по группам.

Например:

- количество пользователей по странам;
- средний баланс по странам;
- средний возраст по странам.

Обычно `GROUP BY` используется вместе с агрегатными функциями.

## Задание 8. Количество пользователей по странам

In [ ]:
run_sql('''
SELECT
    country,
    COUNT(*) AS users_count
FROM users
GROUP BY country;
''')

  country  users_count
0     RUS            4
1     USA            2

## Задание 9. Средний баланс по странам

In [ ]:
run_sql('''
SELECT
    country,
    AVG(balance) AS avg_balance
FROM users
GROUP BY country;
''')

  country  avg_balance
0     RUS      93750.0
1     USA     105000.0

## Задание 10. Средний возраст по странам

In [ ]:
run_sql('''
SELECT
    country,
    AVG(age) AS avg_age
FROM users
GROUP BY country;
''')

  country  avg_age
0     RUS    25.75
1     USA    27.00

## Задание 11. Несколько показателей по странам

In [ ]:
run_sql('''
SELECT
    country,
    COUNT(*) AS users_count,
    AVG(age) AS avg_age,
    AVG(balance) AS avg_balance,
    MIN(balance) AS min_balance,
    MAX(balance) AS max_balance
FROM users
GROUP BY country;
''')

  country  users_count  avg_age  avg_balance  min_balance  max_balance
0     RUS            4    25.75      93750.0      90000.0     100000.0
1     USA            2    27.00     105000.0     100000.0     110000.0

# 15. Сортировка результата группировки

Результат группировки тоже можно сортировать.

Например, отсортируем страны по среднему балансу по убыванию.

In [ ]:
run_sql('''
SELECT
    country,
    AVG(balance) AS avg_balance
FROM users
GROUP BY country
ORDER BY avg_balance DESC;
''')

  country  avg_balance
0     USA     105000.0
1     RUS      93750.0

## Обсуждение

Ответьте на вопросы:

1. Что делает `GROUP BY`?
2. Почему `GROUP BY` часто используется вместе с `COUNT`, `AVG`, `SUM`?
3. Чем группировка похожа на сводную таблицу в Excel?
4. Почему результат группировки полезен для аналитического отчёта?

# 16. Мини-задание для закрепления

Выполните SQL-запросы самостоятельно или вместе с преподавателем.

## Задание

Используя таблицу `users`, выполните запросы:

1. Выведите всех пользователей.
2. Выведите только `name`, `country`, `balance`.
3. Найдите пользователей младше 26 лет.
4. Найдите пользователей из `USA`.
5. Найдите пользователей из `RUS` с балансом больше 90 000.
6. Отсортируйте пользователей по возрасту по убыванию.
7. Найдите пользователя с минимальным балансом.
8. Посчитайте количество пользователей по каждой стране.
9. Посчитайте средний баланс по каждой стране.
10. Сформулируйте один аналитический вывод по результатам.

## Решение мини-задания

### 1. Все пользователи

In [ ]:
run_sql('''
SELECT * FROM users;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   2    Gleb    gleb@example.com   26     RUS   90000.0
2   3  Sergey  sergey@example.com   28     RUS   90000.0
3   4  Andrew  andrew@example.com   24     RUS   95000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   6     Tom     tom@example.com   29     USA  110000.0

### 2. Только name, country, balance

In [ ]:
run_sql('''
SELECT name, country, balance FROM users;
''')

     name country   balance
0    Ivan     RUS  100000.0
1    Gleb     RUS   90000.0
2  Sergey     RUS   90000.0
3  Andrew     RUS   95000.0
4     Bob     USA  100000.0
5     Tom     USA  110000.0

### 3. Пользователи младше 26 лет

In [ ]:
run_sql('''
SELECT * FROM users WHERE age < 26;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   4  Andrew  andrew@example.com   24     RUS   95000.0
2   5     Bob     bob@example.com   25     USA  100000.0

### 4. Пользователи из USA

In [ ]:
run_sql('''
SELECT * FROM users WHERE country = 'USA';
''')

   id name            email  age country   balance
0   5  Bob  bob@example.com   25     USA  100000.0
1   6  Tom  tom@example.com   29     USA  110000.0

### 5. Пользователи из RUS с балансом больше 90 000

In [ ]:
run_sql('''
SELECT * FROM users WHERE country = 'RUS' AND balance > 90000;
''')

   id    name               email  age country   balance
0   1    Ivan    ivan@example.com   25     RUS  100000.0
1   4  Andrew  andrew@example.com   24     RUS   95000.0

### 6. Сортировка по возрасту по убыванию

In [ ]:
run_sql('''
SELECT * FROM users ORDER BY age DESC;
''')

   id    name               email  age country   balance
0   6     Tom     tom@example.com   29     USA  110000.0
1   3  Sergey  sergey@example.com   28     RUS   90000.0
2   2    Gleb    gleb@example.com   26     RUS   90000.0
3   1    Ivan    ivan@example.com   25     RUS  100000.0
4   5     Bob     bob@example.com   25     USA  100000.0
5   4  Andrew  andrew@example.com   24     RUS   95000.0

### 7. Пользователь с минимальным балансом

In [ ]:
run_sql('''
SELECT * FROM users ORDER BY balance ASC LIMIT 1;
''')

   id  name             email  age country  balance
0   2  Gleb  gleb@example.com   26     RUS  90000.0

### 8. Количество пользователей по странам

In [ ]:
run_sql('''
SELECT country, COUNT(*) AS users_count FROM users GROUP BY country;
''')

  country  users_count
0     RUS            4
1     USA            2

### 9. Средний баланс по странам

In [ ]:
run_sql('''
SELECT country, AVG(balance) AS avg_balance FROM users GROUP BY country;
''')

  country  avg_balance
0     RUS      93750.0
1     USA     105000.0

## Пример аналитического вывода

По результатам запросов можно сделать вывод, что в таблице больше пользователей из страны `RUS`, однако средний баланс пользователей из `USA` выше. Это показывает, что простая группировка позволяет быстро сравнивать показатели между категориями.

# 17. Частые ошибки в SQL

## Ошибка 1. Забыли кавычки у текста

Неправильно:

```sql
WHERE country = RUS
```

Правильно:

```sql
WHERE country = 'RUS'
```

---

## Ошибка 2. Забыли FROM

Неправильно:

```sql
SELECT name, age;
```

Правильно:

```sql
SELECT name, age
FROM users;
```

---

## Ошибка 3. Неправильный порядок команд

Обычно порядок такой:

```sql
SELECT ...
FROM ...
WHERE ...
GROUP BY ...
ORDER BY ...
LIMIT ...
```

---

## Ошибка 4. Использование агрегата без понимания группировки

Если нужно посчитать средний баланс по странам, недостаточно написать только `AVG(balance)`.  
Нужно добавить `GROUP BY country`.

# 18. Контрольные вопросы по третьей паре

Ответьте на вопросы:

1. Что такое SQL?
2. Что такое база данных?
3. Что такое таблица?
4. Что такое строка и столбец?
5. Что такое первичный ключ?
6. Что делает команда `SELECT`?
7. Для чего используется `WHERE`?
8. Чем `AND` отличается от `OR`?
9. Для чего используется `BETWEEN`?
10. Что делает `ORDER BY`?
11. Для чего нужен `LIMIT`?
12. Какие агрегатные функции вы знаете?
13. Что делает `GROUP BY`?
14. Почему `GROUP BY` важен для аналитики?
15. Чем SQL-запрос похож на задачу аналитика?

# 19. Итог пары

На третьей паре мы изучили основы SQL на примере одной таблицы `users`.

Мы научились:

- создавать базу данных SQLite;
- создавать таблицу;
- добавлять данные;
- выполнять `SELECT`;
- выбирать отдельные столбцы;
- использовать псевдонимы `AS`;
- фильтровать данные через `WHERE`;
- использовать условия `AND`, `OR`, `BETWEEN`;
- сортировать данные через `ORDER BY`;
- ограничивать результат через `LIMIT`;
- использовать агрегатные функции;
- группировать данные через `GROUP BY`.

## Связь с четвёртой парой

На четвёртой паре мы перейдём к работе с несколькими таблицами.

Мы создадим таблицу `orders`, свяжем её с таблицей `users` и изучим:

- связь таблиц через ключи;
- вычисляемые поля;
- `INNER JOIN`;
- `LEFT JOIN`;
- поиск пользователей без заказов;
- расчёт общей суммы заказов по пользователям.

Это позволит перейти от простых SQL-запросов к полноценным аналитическим задачам.